# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-04 05:01
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
from newsroomFramework.settings import PROJECT_ROOT
import os

def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Namespace = apps.get_model("cms", "Namespace")
    db_alias = schema_editor.connection.alias
    Namespace.objects.using(db_alias).bulk_create([
        Namespace(rdf=open(os.path.join(PROJECT_ROOT, 'root-ontology.owl'),'r').read()),
    ])

def reverse_func(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    Namespace = apps.get_model("cms", "Namespace")
    db_alias = schema_editor.connection.alias
    Namespace.objects.using(db_alias).all().delete()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('sutian', models.CharField(max_length=50)),
                ('text', ckeditor.fields.RichTextField(default='', verbose_name='Matéria')),
                ('relatedTexts', models.TextField(blank=True, max_length=50, null=True, verbose_name='URL relacionadas')),
            ],
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Editoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topico', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Namespace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdf', models.TextField(verbose_name='rdf')),
            ],
        ),
        migrations.CreateModel(
            name='Publicado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField(verbose_name='html')),
                ('rdf_annotation', models.TextField(verbose_name='rdf_annotation')),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Artigo')),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', ckeditor.fields.RichTextField(verbose_name='uri')),
                ('valor', ckeditor.fields.RichTextField(verbose_name='valor')),
                ('namespace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Namespace')),
            ],
        ),
        migrations.CreateModel(
            name='Tripla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Artigo')),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objeto', to='cms.Recurso')),
                ('predicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicado', to='cms.Recurso')),
            ],
        ),
        migrations.AddField(
            model_name='artigo',
            name='creators',
            field=models.ManyToManyField(to='cms.Creator'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='editoria',
            field=models.ManyToManyField(to='cms.Editoria'),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
