# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 14:02
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
from cms.models import ChoiceArrayField,Widget


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('sutian', models.CharField(max_length=50)),
                ('text', ckeditor.fields.RichTextField(default='', verbose_name='Matéria')),
                #('semanticAnnotationsPath',ChoiceArrayField(base_field=models.CharField(max_length=100),blank=True,null=True)),
                #('semanticAnnotationsPath', models.TextField(max_length=50, verbose_name='Path para a Anotação Semântica')),
                ('semanticAnnotationsPath', Widget()),
                ('relatedTexts', models.TextField(max_length=50, verbose_name='URL relacionadas')),
            ],
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Editoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topico', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='artigo',
            name='creators',
            field=models.ManyToManyField(to='cms.Creator'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='editoria',
            field=models.ManyToManyField(to='cms.Editoria'),
        ),
    ]
