# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-04 05:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigo',
            name='relatedTexts',
        ),
    ]
